### ISSUE TITLE
Invalid Token Error

### ISSUE THREAD

**Issue by travismoore589** [AlecM33/quote-bot#6]
I keep receiving an invalid token error after running npm start. I have installed discord.js and added an env file with the required variables. Am I missing another step, or should I be adding the variables in another location? Thanks.

**Comment by AlecM33** [comment]
Hello! If you debug and observe the actual value passed to `.login()` within `main.js`, does it match the token you are expecting? The simplest things to rule out would be a failure to resolve your variable, or the variable doesn't match the latest token Discord has generated in the Bot section of the Discord App you created. Sometimes discord will regenerate your token if it detects it became compromised, for example.

Regards

**Comment by AlecM33** [comment]
@travismoore589 just following up here - I do see that your token was committed to your public repo, which will result in discord automatically revoking the token. Careful about that. If you encounter other issues feel free to let me know. 

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation#token-revoked-when-pushed-to-a-public-repository-or-public-gist
